### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getBuffer' of undefined

### ISSUE THREAD

**Issue by pl-kabaradjian** [34yu34/header-implementation#1]
[Enter steps to reproduce:]

1. Be in the wrong file (or maybe in a cpp file with no header in the same folder)
2. Try to update the file

**Atom**: 1.23.1 x64
**Electron**: 1.6.15
**OS**: Ubuntu 16.04.3
**Thrown From**: [header-implementation](https://github.com/34yu34/header-implementation) package 0.4.0

### Stack Trace

Uncaught TypeError: Cannot read property 'getBuffer' of undefined

```
At /home/plk/.atom/packages/header-implementation/lib/header-implementation.coffee:247

TypeError: Cannot read property 'getBuffer' of undefined
    at Object.generateWork (/packages/header-implementation/lib/header-implementation.coffee:247:20)
    at Object.update (/packages/header-implementation/lib/header-implementation.coffee:307:13)
    at /packages/header-implementation/lib/header-implementation.coffee:12:43)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:388:36)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom/resources/app/src/window-event-handler.js:108:40)
```

### Commands

```
  3x -5:49.9.0 core:backspace (input.hidden-input)
     -5:48.6.0 intentions:highlight (input.hidden-input)
     -5:48.5.0 core:save (input.hidden-input)
  2x -5:08.8.0 core:confirm (input.hidden-input)
  6x -2:25.1.0 core:backspace (input.hidden-input)
     -2:19.3.0 core:confirm (input.hidden-input)
     -2:04.2.0 core:backspace (input.hidden-input)
     -2:02.2.0 core:confirm (input.hidden-input)
     -0:55.9.0 intentions:highlight (input.hidden-input)
     -0:55.5.0 header-implementation:generate (input.hidden-input)
     -0:49.3.0 intentions:highlight (input.hidden-input)
     -0:48.8.0 core:save (input.hidden-input)
     -0:19.3.0 intentions:highlight (input.hidden-input)
     -0:18.5.0 header-implementation:update (input.hidden-input)
     -0:16.7.0 intentions:highlight (input.hidden-input)
  7x -0:16.2.0 header-implementation:update (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.9 
busy-signal 1.4.3 
header-implementation 0.4.0 
intentions 1.1.5 
linter 2.2.0 
linter-pycodestyle 2.1.3 
linter-ui-default 1.6.10 
platformio-ide-terminal 2.7.0 
teletype 0.4.0 
term 0.2.4 
```

**Comment by Hyftar** [comment]
Thank you for your contribution! I'll try to push a fix for it in the next few days. Stay tuned!
